name: .NET Core Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    strategy:
        matrix:
          configuration: [Debug, Release]

    runs-on: windows-latest
    
    env:
      Solution_Name: Outlines.sln

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
        
    - name: 'Publish Outlines App'
      uses: actions/upload-artifact@v2
      with:	
        name: 'Outlines App'	
        path: '.\Outlines.App\bin\${{matrix.configuration}}\netcoreapp3.1\'
