name: .NET Core Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    strategy:
        matrix:
          configuration: [Debug, Release]

    runs-on: windows-latest
    
    env:
      Solution_Name: Outlines.sln

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Restore Solution
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:${{matrix.configuration}} /p:Platform="Any CPU"

    - name: Build Solution
      run: msbuild $env:Solution_Name /p:Configuration=${{matrix.configuration}} p:Platform="Any CPU"
    
    - name: 'Publish Outlines App'
      uses: actions/upload-artifact@v2
      with:	
        name: 'Outlines App'	
        path: '.\Outlines.App\bin\${{matrix.configuration}}\net6.0-windows10.0.22000\'
